repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.5
    hooks:
      - id: ruff
        language_version: python3.10
        args: ["--fix"]

      - id: ruff-format
        language_version: python3.10
        

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.12.0
    hooks:
      - id: mypy
        language_version: python3.10
        additional_dependencies:
          - pydantic
          - pydantic-settings
          - types-requests
